name: e2e tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PACKAGEPATH: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  tests:
    # e2e tests depend on docker. Docker is not available on macos github actions
    # https://github.community/t/why-is-docker-not-installed-on-macos/17017
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ${{ env.PACKAGEPATH }}
      - name: Build image
        working-directory: ${{ env.PACKAGEPATH }}
        run: docker build . --file Dockerfile-e2e-tests --tag xdsrelay
      - name: run e2e tests inside container
        run: docker run -v ${{ env.PACKAGEPATH }}:/xds-relay xdsrelay:latest make e2e-tests
