name: e2e tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    # e2e tests depend on docker. Docker is not available on macos github actions
    # https://github.community/t/why-is-docker-not-installed-on-macos/17017
    runs-on: ubuntu-latest
    steps:
      - run: echo "PACKAGEPATH=${{ github.workspace }}/go/src/github.com/${{ github.repository }}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.PACKAGEPATH }}
      - name: Build image
        working-directory: ${{ env.PACKAGEPATH }}
        run: docker build . --file Dockerfile-e2e-tests --tag xdsrelay
      - name: run e2e tests inside container
        run: docker run -v ${{ env.PACKAGEPATH }}:/xds-relay xdsrelay:latest make e2e-tests
